In [12]:
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('data.txt', index_col=0)

In [20]:
df

X   Y  Class
id               
1   19  73      1
2   68  94      1
3   34  33      0
4   76  69      1
5   37  71      0
6   45  79      0
7   20  30      0
8   91  42      0
9   33  82      1
10  66  23      0

In [21]:
# нужно найти ближайший элемент к (99, 49) 
df_test = pd.DataFrame({'X': [99], 'Y': [49]})

neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(df[['X', 'Y']])

print(neigh.kneighbors(df_test)) # первое число это расстояние, второе номер элемента (нумерация с 0)

(array([[10.63014581]]), array([[7]], dtype=int64))


In [25]:
# 3 ближайших
neigh = NearestNeighbors(n_neighbors=3)
neigh.fit(df[['X', 'Y']])

print(neigh.kneighbors(df_test)) # первое число это расстояние, второе номер элемента (нумерация с 0)

(array([[10.63014581, 30.47950131, 42.01190308]]), array([[7, 3, 9]], dtype=int64))


In [26]:
# класс для объекта (99,49)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(df.drop(columns='Class'), df['Class'])

neigh.predict(df_test)

array([0], dtype=int64)

In [27]:
# расстояние до ближайшего соседа по манхэттену

neigh = NearestNeighbors(n_neighbors=1, p=1)
neigh.fit(df[['X', 'Y']])

print(neigh.kneighbors(df_test)) # первое число это расстояние, второе номер элемента (нумерация с 0)

(array([[15.]]), array([[7]], dtype=int64))


In [28]:
# 3 ближайших по манхэттену
neigh = NearestNeighbors(n_neighbors=3, p=1)
neigh.fit(df[['X', 'Y']])

print(neigh.kneighbors(df_test)) # первое число это расстояние, второе номер элемента (нумерация с 0)

(array([[15., 43., 59.]]), array([[7, 3, 9]], dtype=int64))


In [29]:
# класс для объекта (99,49) по манхэттену

neigh = KNeighborsClassifier(n_neighbors=3, p=1)
neigh.fit(df.drop(columns='Class'), df['Class'])

neigh.predict(df_test)

array([0], dtype=int64)